name = "yt-clip-api"
compatibility_date = "2024-10-14"
pages_build_output_dir = "frontend/dist"

[[d1_databases]]
binding = "DB"
database_name = "ytclipdb"
database_id = "849d3d66-df7e-4f39-b03b-72dd11ee266d"
migrations_dir = "migrations"
